[workspace]
resolver = "3"
members = [
    "crates/api/client",
    "crates/api/ui",
    "crates/client",
    "crates/core",
    "crates/server",
    "crates/shared",
    "crates/tftp",
    "crates/web",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread", "process"] }
imaged-shared = { path = "crates/shared", default-features = false }
injectable = "0.1.0"
tokio-stream = { version = "0.1", features = ["sync"] }
derive_more = { version = "2.1.1", features = ["constructor"] }
tracing = "0.1"
futures = "0.3.32"
thiserror = "2.0.18"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio-util = "0.7.18"
clap = { version = "4.6.1", features = ["derive", "env"] }
