services:
  dnsmasq:
    image: jpillora/dnsmasq
    networks:
      pxenet:
        ipv4_address: 192.168.100.2
    cap_add:
      - NET_ADMIN
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf:ro
    restart: unless-stopped

networks:
  pxenet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-netboot
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
          ip_range: 192.168.100.16/28
