[package]
name = "imaged-client"
version.workspace = true
edition.workspace = true

[lib]
name = "imaged_client"
path = "src/lib.rs"

[[bin]]
name = "imaged-client"
path = "src/main.rs"

[dependencies]
tracing.workspace = true
tokio.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
imaged-shared = { workspace = true, features = ["all"] }
api = { package = "imaged-api-client", path = "../api/client" }
tokio-util.workspace = true
derive_more = { workspace = true, features = ["display"] }
clap.workspace = true
dioxus-fullstack = "0.7"

async-compression = { version = "0.4", features = ["tokio", "zstd"] }

mac_address = "1.1.8"
anyhow = "1.0.102"
rustix = { version = "1.1.4", features = ["termios", "stdio", "system"] }
enum_dispatch = "0.3.13"
local-ip-address = "0.6.13"

[dev-dependencies]
axum = "0.8"
tokio = { workspace = true, features = ["net", "io-util", "fs", "time"] }
