[package]
name = "imaged-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "imaged-server"
path = "src/main.rs"

[dependencies]
dioxus = { version = "0.7", features = ["fullstack", "router"] }
imaged-web = { path = "../web" }

imaged-api-ui = { path = "../api/ui", optional = true }
imaged-api-client = { path = "../api/client", optional = true }
imaged-core = { path = "../core", optional = true }
imaged-shared = { workspace = true, features = ["logging"], optional = true }
axum = { version = "0.8", optional = true }
tokio = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }

[features]
default = []
server = [
    "dioxus/server",
    "imaged-web/server",
    "dep:imaged-api-ui",
    "imaged-api-ui/server",
    "dep:imaged-api-client",
    "imaged-api-client/server",
    "dep:imaged-core",
    "dep:imaged-shared",
    "dep:axum",
    "dep:tokio",
    "dep:clap",
    "dep:tracing",
]
web = ["dioxus/web", "imaged-web/web"]
