name: Build and push to Cachix

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - .#imaged-server
          - .#imaged-tftp
          - .#kernel
          - .#devShells.x86_64-linux.default.inputDerivation
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v17
        with:
          name: luukblankenstijn
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - run: nix build '${{ matrix.target }}' --print-build-logs
